"""add vehicles table

Revision ID: 33632a5702b6
Revises: 
Create Date: 2026-08-07 15:21:13.188946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33632a5702b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fleet_id', sa.String(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('battery_capacity', sa.Float(), nullable=False),
    sa.Column('max_range', sa.Float(), nullable=False),
    sa.Column('assigned_driver', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('available', 'in-use', 'service', name='vehicle_status'), nullable=False),
    sa.Column('battery_percent', sa.Float(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('range', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_id'),
    sa.UniqueConstraint('vin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
