"""add_km_driven_energy_kwh_to_activity

Revision ID: 51aa1be783af
Revises: 8e0ab5d7b81d
Create Date: 2026-08-07 15:59:35.820120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51aa1be783af'
down_revision: Union[str, None] = '8e0ab5d7b81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('km_driven', sa.Float(), nullable=True))
    op.add_column('activity_logs', sa.Column('energy_kwh', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'energy_kwh')
    op.drop_column('activity_logs', 'km_driven')
    # ### end Alembic commands ###
