"""add_employees_activities_notifications

Revision ID: 890855fab005
Revises: 33632a5702b6
Create Date: 2026-08-07 15:28:20.645753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890855fab005'
down_revision: Union[str, None] = '33632a5702b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('vehicle_name', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('driver', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'in-progress', 'pending', name='activity_status'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'on-leave', 'inactive', name='employee_status'), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('initials', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='template_status'), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('phone_count', sa.Integer(), nullable=False),
    sa.Column('last_sent', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_templates')
    op.drop_table('employees')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
